#  Docker Compose сам автоматически подхватывает .env только для подстановки в docker-compose.yml (например ${VAR}), но не в контейнер.
#  Если хочешь, чтобы Node.js или любое другое приложение внутри контейнера реально видело эти переменные — нужно явно указать:
#  env_file:
#    - ./.env

# :ro - read only

networks:
  shared_network:
    external: true
  internal_network:
    name: "${PROJECT_PREFIX}-internal_network"
    driver: bridge

volumes:
  db-data:

services:
  db:
    image: postgres:17-alpine
    container_name: "${PROJECT_PREFIX}-db"
    shm_size: 128mb
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - internal_network

  cms:
    container_name: "${PROJECT_PREFIX}-cms"
    restart: always
    environment:
      HOST: ${CMS_HOST}
      PORT: ${CMS_PORT}
      APP_KEYS: ${CMS_APP_KEYS}
      API_TOKEN_SALT: ${CMS_API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${CMS_ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${CMS_TRANSFER_TOKEN_SALT}
      ENCRYPTION_KEY: ${CMS_ENCRYPTION_KEY}
      JWT_SECRET: ${CMS_JWT_SECRET}
      DATABASE_CLIENT: "postgres"
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${POSTGRES_PORT}
      DATABASE_NAME: "cms"
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_SSL: false
      DATABASE_FILENAME: ""
    ports:
      - "${CMS_PORT}:${CMS_PORT}"
    networks:
      - internal_network
